# USER_ID=$(id -u):$(id -g) docker-compose up -d

version: '3'
services:
  MathFinder:
    build:
      context: .
      dockerfile: Dockerfile
    image: jpatrick1/mathfinder
    hostname: mf
    user: $USER_ID
    volumes:
#      - ./training:/.mathfinder/training
      - ./data/Groundtruth/WithoutLabels:/data
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - USER=$USER
      - DISPLAY=$DISPLAY
      - LD_LIBRARY_PATH=/usr/local/lib
      - TESSDATA_PREFIX=/usr/local/share
      - SCROLLVIEW_PATH=/usr/local/share/scrollview
    working_dir: /.mathfinder/groundtruth/
    ports:
      - 9030:9030
    
    # drop into bash shell
    # useful for bind mounting data and doing a training session
    # run MathFinder -m to get training menu
#    entrypoint: bash

    # run http server
    #    entrypoint: python -m mathfinder.server
